export const slider = [
  {
    sliderHeading: "Pricing & Plan",
    sliderParagrafh: "950 PKR / MONTH",
    list: [
      "S*mrush ( 30 Serches a Day )",
      "Instr0id ( Plagarism & Ai )",
      "M@ngools",
      "Link Indexer",
      "p*k To Chart",
      "Uber-Suggest",
      " Mooz pro",
      "Serp-stat",
      "Storybase",
      "Spyfu",
      "Woo-Rank",
      "Long Tail Pro",
      "Spin Rewriter",
      "Grammerly",
      "Canva",
      "Scribd",
      "Prime Video",
      "Pluralsight",
      "SkillShare",
      "Seoability",
      "Coming Soon*",
    ],
  },
  {
    sliderHeading: "All in One Package",
    sliderParagrafh: "1,350 PKR / MONTH",
    list: [
      "Rytr.me ( Testing tool )",
      "Semrush ( 30 Serches a Day )",
      "StoryBlocks (30 Downloads Per Day)",
      "ManG!ools Tools",
      "Placeit",
      "GrowthBar",
      "Instr0id ( Plagarism & Ai )",
      "Vecteezy",
      "P*k To chart",
      "In-Video",
      "Powtoon",
      "WordTune",
      "Epidemic - Sounds",
      "UberSuggest",
      "Link Indexer",
      "Grammerly",
      "Mooz pro",
      "Serp-stat",
      "StoryBase",
      "Spyfu",
      "Woo-Rank",
      "View More",
    ],
  },
  {
    sliderHeading: "Designers Package",
    sliderParagrafh: "900 PKR / MONTH",
    list: [
      "Motion Arry",
      "UpLabs",
      "Creative Fabrica",
      "Powtoon",
      "Magisto",
      "Pik To",
      "Placit",
      "Pics Art",
      "Skill Share",
      "PluralSight",
      "Spin Rewriter",
      "Crello",
      "Canva",
      "Scribd",
      "Prime Video",
      "Comming Soon",
    ],
  },
];
