import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import HeroSection from "../components/HeroSection";
import Divider from "../components/Divider";
import DragonAffordable from "../components/DragonAffordable";
import ClientDragon from "../components/ClientDragon";
import FaqDragon from "../components/FaqDragon";
import ImportantDragon from "../components/ImportantDragon";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        {/* <ClientDragon /> */}
        {/* <FaqDragon /> */}
        <ImportantDragon />
        {/* <HeroSection /> */}
        {/* <Divider /> */}
        {/* <DragonAffordable /> */}
        {/* <Footer /> */}
      </main>
    </div>
  );
}
