import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import HeroSection from "../components/HeroSection";
import Divider from "../components/Divider";
import DragonAffordable from "../components/DragonAffordable";
import ClientDragon from "../components/ClientDragon";
import FaqDragon from "../components/FaqDragon";
import ImportantDragon from "../components/ImportantDragon";
import ChoosingDragon from "../components/ChoosingDragon";
import DragonSlider from "../components/DragonSlider";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dragon Client</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <ClientDragon />
        <FaqDragon />
        <HeroSection />
        <Divider />
        <DragonAffordable />
        <ChoosingDragon />
        <DragonSlider />
        <ClientDragon />
        <FaqDragon />
        <ImportantDragon />
        <Footer />
      </main>
    </div>
  );
}
